parameters:
#    proces_cursos.example.class: Proces\CursosBundle\Example

services:
#    proces_cursos.example:
#        class: %proces_cursos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
