<?php

namespace Proces\OfertaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PasosOfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasosOfertaRepository extends EntityRepository
{
}
