parameters:
#    ica_tramite.example.class: ICA\TramiteBundle\Example

services:
#    ica_tramite.example:
#        class: %ica_tramite.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
