<?php

namespace ICA\TramiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EspecieAnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspecieAnimalRepository extends EntityRepository
{
}
