<?php

namespace ICA\TramiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MotivoIdentificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivoIdentificacionRepository extends EntityRepository
{
}
