<?php

namespace ICA\TramiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RangoEdadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RangoEdadesRepository extends EntityRepository
{
}
