web:
    resource: "@WebBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

themes:
    resource: "@ThemesBundle/Resources/config/routing.yml"
    prefix:   /themes

proces_cursos:
    resource: "@ProcesCursosBundle/Resources/config/routing.yml"
    prefix:   /cursos

ica_tramite:
    resource: "@ICATramiteBundle/Resources/config/routing.yml"
    prefix:   /icatramite

oficinas_prueba:
    resource: "@OficinasBundle/Resources/config/routing.yml"
    prefix:   /oficinas

servicios:
    resource: "@ServiciosBundle/Resources/config/routing.yml"
    prefix:   /servicios

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /oferta
    


usuarios:
    resource: "@UsuariosBundle/Resources/config/routing.yml"
    prefix:   /usuarios