security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:         ROLE_USER
        ROLE_SOLICITUDES: [ROLE_USER]
        ROLE_SERVICIOS:   [ROLE_USER]
        ROLE_CONVOCATOR:  [ROLE_USER]  
        ROLE_TRAMITES:    [ROLE_USER]
        ROLE_OFERTAS:     [ROLE_OFERTAS]  
        ROLE_ADMIN:       [ROLE_USER, ROLE_CONVOCATOR, ROLE_SERVICIOS, ROLE_TRAMITES, ROLE_OFERTAS]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SOLICITUDES, ROLE_CONVOCATOR, ROLE_SERVICIOS, ROLE_TRAMITES, ROLE_OFERTAS, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            id: fos_user.user_provider.username_email
        in_memory:
            memory:
                users:
                    user:  { password: user, roles: [ 'ROLE_USER' ] }
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
       
        administrador:
            pattern: ^/admin
            context: primary_auth
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
              path:       admin_logout
              target:     /
              invalidate_session: false
            anonymous:    true
       
        main:
            pattern: ^/usuarios
            context: primary_auth
            form_login:
                default_target_path: /usuarios/profile
                always_use_default_target_path: true
                login_path: /usuarios/login/
                check_path: /usuarios/login_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
              path:       usuarios_logout
              target:     /admin
              invalidate_session: false
            anonymous:    true
        
        entrada:
            pattern: ^/
            anonymous:    true    

    access_control:
        
        - { path: ^/admin/login$,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/servicios/*, role: [ROLE_SERVICIOS, ROLE_ADMIN] }
        - { path: ^/admin/convocatorias/*, role: [ROLE_CONVOCATOR, ROLE_ADMIN] }        
        - { path: ^/admin/ofertas-institucionales/*, role: [ROLE_OFERTAS, ROLE_ADMIN] }
        - { path: ^/admin/cursosvirtuales/*, role: [ROLE_OFERTAS, ROLE_ADMIN] }
        - { path: ^/admin/oficinas/*, role: [ROLE_OFICINA, ROLE_ADMIN] }
        - { path: ^/admin/departamento/*, role: [ROLE_OFICINA, ROLE_ADMIN] }
        - { path: ^/admin/municipio/*, role: [ROLE_OFICINA, ROLE_ADMIN] } 
        - { path: ^/admin/solmantenimiento/*, role: [ROLE_SOLICITUDES] }
        - { path: ^/admin/estado/*, role: [ROLE_SOLICITUDES, ROLE_ADMIN] }
        - { path: ^/admin/seccionales/*, role: [ROLE_SOLICITUDES, ROLE_ADMIN] }
        - { path: ^/admin/especieanimal/*, role: [ROLE_SOLICITUDES, ROLE_ADMIN] }
        - { path: ^/admin/rangoedades/*, role: [ROLE_SOLICITUDES, ROLE_ADMIN] }  
        - { path: ^/admin/motivoidentificacion/*, role: [ROLE_SOLICITUDES, ROLE_ADMIN] }                         
        - { path: ^/admin, roles: [ROLE_OFICINA,  ROLE_SOLICITUDES,  ROLE_SERVICIOS,  ROLE_CONVOCATOR,  ROLE_TRAMITES,  ROLE_ADMIN]  }        
        - { path: ^/usuarios/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuarios/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuarios/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuarios/admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/*,  role: IS_AUTHENTICATED_ANONYMOUSLY }