convocatorias_logout:
    pattern:  /logout

convocatorias_homepage:
    path:     /
    defaults: { _controller: ConvocatoriasBundle:Default:index }

ConvocatoriasBundle_convocatorias:
    resource: "@ConvocatoriasBundle/Resources/config/routing/convocatorias.yml"
    prefix:   /convocatorias

