parameters:
#    convocatorias.example.class: Proces\ConvocatoriasBundle\Example

services:
#    convocatorias.example:
#        class: %convocatorias.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
