<?php

namespace Proces\OficinasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DepartamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartamentoRepository extends EntityRepository
{
    public function findDepartamentostotal()
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT d.id, d.nombreDepartamento FROM OficinasBundle:Departamento d');
        
        $resultado = $consulta->getArrayResult();
        return $resultado;
    }
}
