<?php

namespace Proces\OficinasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OficinasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OficinasRepository extends EntityRepository
{
}
