parameters:
#    usuarios.example.class: Proces\UsuariosBundle\Example

services:
    mi_propio.registration.form.type:
        class: Proces\UsuariosBundle\Form\UserType
        tags:
            - { name: form.type, alias: mi_user_registration }