<?php

namespace Proces\ConvocatoriasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConvocatoriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvocatoriasRepository extends EntityRepository
{
}
