<?php

namespace Proces\ConvocatoriasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConvocatoriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvocatoriasRepository extends EntityRepository
{
    public function findConvocatoriastotal()
    {
        
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT o.id, u.id AS usuario_id, o.descripcion, o.urlConvocatoria, o.descripcionLarga, o.tituloConvocatoria FROM ConvocatoriasBundle:Convocatorias o JOIN o.usuario u');
        
        $resultado = $consulta->getArrayResult();
        return $resultado;
    }
    
    public function findConvocatorias()
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT COUNT(o) AS Cuenta FROM ConvocatoriasBundle:Convocatorias o');
        $resultado = $consulta->getArrayResult();
        return $resultado;
    }
}
