admin_login:
    pattern:  /login
    defaults: { _controller: AdminBundle:Default:login }

admin_login_check:
    pattern:  /login_check

admin_logout:
    pattern:  /logout
    
admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Admin:index }

Admin_OficinasBundle_oficinas:
        resource: "@OficinasBundle/Resources/config/routing/oficinas.yml"
        prefix:   /oficinas

convocatorias:
    resource: "@ConvocatoriasBundle/Resources/config/routing.yml"
    prefix:   /convocatorias


WebBundle_solmantenimientoidentificacion:
    resource: "@WebBundle/Resources/config/routing/solmantenimientoidentificacion.yml"
    prefix:   /solmantenimiento
    
servicios_servicios:
    resource: "@ServiciosBundle/Resources/config/routing/servicios.yml"
    prefix:   /servicios
    
oferta_ofertasinstitucionales:
    resource: "@OfertaBundle/Resources/config/routing/ofertasinstitucionales.yml"
    prefix:   /ofertas-institucionales
    
proces_cursos_cursosvirtuales:
    resource: "@ProcesCursosBundle/Resources/config/routing/cursosvirtuales.yml"
    prefix:   /cursosvirtuales

ICATramiteBundle_seccionales:
    resource: "@ICATramiteBundle/Resources/config/routing/seccionales.yml"
    prefix:   /seccionales

ICATramiteBundle_especieanimal:
    resource: "@ICATramiteBundle/Resources/config/routing/especieanimal.yml"
    prefix:   /especieanimal

ICATramiteBundle_rangoedades:
    resource: "@ICATramiteBundle/Resources/config/routing/rangoedades.yml"
    prefix:   /rangoedades

ICATramiteBundle_motivoidentificacion:
    resource: "@ICATramiteBundle/Resources/config/routing/motivoidentificacion.yml"
    prefix:   /motivoidentificacion

WebBundle_solicitudcantidadmotivo:
    resource: "@WebBundle/Resources/config/routing/solicitudcantidadmotivo.yml"
    prefix:   /solicitudcantidadmotivo

WebBundle_especierangosolicitud:
    resource: "@WebBundle/Resources/config/routing/especierangosolicitud.yml"
    prefix:   /especierangosolicitud


OficinasBundle_departamento:
    resource: "@OficinasBundle/Resources/config/routing/departamento.yml"
    prefix:   /departamento

OficinasBundle_municipio:
    resource: "@OficinasBundle/Resources/config/routing/municipio.yml"
    prefix:   /municipio

oferta_pasosoferta:
    resource: "@OfertaBundle/Resources/config/routing/pasosoferta.yml"
    prefix:   /pasosoferta
    
WebBundle_estado:
    resource: "@WebBundle/Resources/config/routing/estado.yml"
    prefix:   /estado
