admin_login:
    pattern:  /login
    defaults: { _controller: AdminBundle:Default:login }

admin_login_check:
    pattern:  /login_check

admin_logout:
    pattern:  /logout
    
admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Admin:index }
