admin_login:
    pattern:  /login
    defaults: { _controller: AdminBundle:Default:login }

admin_login_check:
    pattern:  /login_check

admin_logout:
    pattern:  /logout
    
admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Admin:index }

Admin_OficinasBundle_oficinas:
        resource: "@OficinasBundle/Resources/config/routing/oficinas.yml"
        prefix:   /oficinas

convocatorias:
    resource: "@ConvocatoriasBundle/Resources/config/routing.yml"
    prefix:   /convocatorias


WebBundle_solmantenimientoidentificacion:
    resource: "@WebBundle/Resources/config/routing/solmantenimientoidentificacion.yml"
    prefix:   /solmantenimiento
    
servicios_servicios:
    resource: "@ServiciosBundle/Resources/config/routing/servicios.yml"
    prefix:   /servicios
    
oferta_ofertasinstitucionales:
    resource: "@OfertaBundle/Resources/config/routing/ofertasinstitucionales.yml"
    prefix:   /ofertas-institucionales
    
proces_cursos_cursosvirtuales:
    resource: "@ProcesCursosBundle/Resources/config/routing/cursosvirtuales.yml"
    prefix:   /cursosvirtuales