<?php

namespace Proces\CursosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CursosVirtualesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursosVirtualesRepository extends EntityRepository
{
    public function findCursostotal()
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT o.id, u.id AS usuario_id, '
                . 'o.nombreCurso, o.descripcionCurso, o.urlAudio, o.urlCurso, o.estado '
                . 'FROM ProcesCursosBundle:CursosVirtuales o JOIN o.usuario u');
        
        $resultado = $consulta->getArrayResult();
        return $resultado;
    }
    public function findCursosActivos()
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT COUNT(o) AS Cuenta FROM ProcesCursosBundle:CursosVirtuales o WHERE o.estado = true');
        $resultado = $consulta->getArrayResult();
        return $resultado;
    }
    
    public function findCursos()
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT o FROM ProcesCursosBundle:CursosVirtuales o WHERE o.estado = true');
        $resultado = $consulta->getArrayResult();
        return $resultado;
    }
}
