<?php

namespace Proces\CursosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CursosVirtualesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursosVirtualesRepository extends EntityRepository
{
}
