<?php

namespace Web\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EspecieRangoSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspecieRangoSolicitudRepository extends EntityRepository
{
}
