<?php

namespace Web\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SolMantenimientoIdentificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolMantenimientoIdentificacionRepository extends EntityRepository
{
    public function findPendientes()
    {
        $estado = "Pendiente";
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT COUNT(o) AS Cuenta FROM WebBundle:SolMantenimientoIdentificacion o 
            WHERE o.estadoSolicitud = :estado ORDER BY o.fechaSolicitud DESC
            '
        );
        $consulta->setParameter('estado', $estado);
        $resultado = $consulta->getArrayResult();
        return $resultado;
    }
}
