parameters:
#    oferta.example.class: Proces\OfertaBundle\Example

services:
#    oferta.example:
#        class: %oferta.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
