parameters:
#    themes.example.class: Proces\ThemesBundle\Example

services:
#    themes.example:
#        class: %themes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
