web_homepage:
    path:     /
    defaults: { _controller: WebBundle:Default:index }

convocatorias_homepage:
    path:     /convocatorias
    defaults: { _controller: ConvocatoriasBundle:Default:index }
    
proces_cursos_homepage:
    path:     /cursos
    defaults: { _controller: ProcesCursosBundle:Default:index }
    
oferta_homepage:
    path:     /ofertas
    defaults: { _controller: OfertaBundle:Default:index }
    
servicios_homepage:
    path:     /servicios
    defaults: { _controller: ServiciosBundle:Default:index }
    
WebBundle_solManten:
    resource: "@WebBundle/Resources/config/routing/sol-mantenimientoidentificacion.yml"
    prefix:   /sol-mantenimiento    

#Web services
web_ofertasPasos:
    path:     /pasos
    defaults: { _controller: WebBundle:Default:Ofertas }

web_ofertasTotal:
    path:     /ofertastotal
    defaults: { _controller: WebBundle:Default:Ofertastotal }  

# formulario ICA

web_icaformulario:
    path:     /crearFormulario/{municipio}/{seccional}/{justificacion}/{ica3101}/{nombreFinca}/{nombrePropietarioFinca}/{cedulaPropietarioFinca}/{telefonoFijoPropietario}/{telefonoCelularPropietario}/{nombreSolicitante}/{cedulaSolicitante}/{telefonoFijoSolicitante}/{telefonoCelularSolicitante}
    defaults: { _controller: "WebBundle:Default:crearFormulario", municipio: null, seccional: null, justificacion: null, ica3101: null, nombreFinca: null, nombrePropietarioFinca: null, cedulaPropietarioFinca: null, telefonoFijoPropietario: null , telefonoCelularPropietario: null, nombreSolicitante: null, cedulaSolicitante: null, telefonoFijoSolicitante: null, telefonoCelularSolicitante: null }
    requirements: { _method: get }
    
