web_homepage:
    path:     /
    defaults: { _controller: WebBundle:Default:index }

convocatorias_homepage:
    path:     /convocatorias
    defaults: { _controller: ConvocatoriasBundle:Default:index }
    
proces_cursos_homepage:
    path:     /cursos
    defaults: { _controller: ProcesCursosBundle:Default:index }

proces_cursosvirtuales_homepage:
    path:     /cursos-virtuales
    defaults: { _controller: ProcesCursosBundle:Default:cursos }
    
oferta_homepage:
    path:     /ofertas
    defaults: { _controller: OfertaBundle:Default:index }
    
servicios_homepage:
    path:     /servicios
    defaults: { _controller: ServiciosBundle:Default:index }
    
WebBundle_solManten:
    resource: "@WebBundle/Resources/config/routing/sol-mantenimientoidentificacion.yml"
    prefix:   /sol-mantenimiento    

#Web services
web_ofertasPasos:
    path:     /pasos
    defaults: { _controller: WebBundle:Default:Ofertas }

web_ofertasTotal:
    path:     /ofertastotal
    defaults: { _controller: WebBundle:Default:Ofertastotal }  

web_convocatoriasTotal:
    path:     /convocatoriastotal
    defaults: { _controller: WebBundle:Default:convocatoriastotal }    

web_cursosTotal:
    path:     /cursostotal
    defaults: { _controller: WebBundle:Default:cursostotal }      

web_serviciosTotal:
    path:     /serviciostotal
    defaults: { _controller: WebBundle:Default:serviciostotal } 

# formulario ICA

web_icaformulario:
    path:     /crearFormulario/{ica3101}/{nombreFinca}/{nombrePropietarioFinca}/{cedulaPropietarioFinca}/{telefonoFijoPropietario}/{telefonoCelularPropietario}/{municipioVereda}/{departamento}/{nombreSolicitante}/{cedulaSolicitante}/{telefonoFijoSolicitante}/{telefonoCelularSolicitante}/{menUnoBovino}/{unoDosBovino}/{dosTresBovino}/{tresMayorBovino}/{menUnoBufalino}/{unoDosBufalino}/{dosTresBufalino}/{tresMayorBufalino}/{jusPrimera}/{jusNacimiento}/{jusCompraAnimales}/{jusPerdidaDin}/{justificacion}/
    defaults: { _controller: "WebBundle:Default:crearFormulario",  ica3101: null, nombreFinca: null,  nombrePropietarioFinca: null, cedulaPropietarioFinca: null, telefonoFijoPropietario: null , telefonoCelularPropietario: null, municipioVereda: null, departamento: null, nombreSolicitante: null, cedulaSolicitante: null, telefonoFijoSolicitante: null, telefonoCelularSolicitante: null, menUnoBovino: null, unoDosBovino: null, dosTresBovino: null, tresMayorBovino: null, menUnoBufalino: null, unoDosBufalino: null, dosTresBufalino: null, tresMayorBufalino: null, jusPrimera: null, jusNacimiento: null, jusCompraAnimales: null, jusPerdidaDin: null, justificacion: null }
    requirements: { _method: get }
    
# Vista web de las páginas    
web_paginas:
    path:     /paginas/
    defaults: { _controller: WebBundle:Default:paginas }    
    
