<?php

namespace Proces\ServiciosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServiciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiciosRepository extends EntityRepository
{
    public function findServiciostotal()
    {
        
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT o.id, u.id AS usuario_id, o.tituloServicio, '
                . 'o.descripcionServicio, o.urlAudioServicio, o.urlServicio '
                . 'FROM ServiciosBundle:Servicios o JOIN o.usuario u');
        
        $resultado = $consulta->getArrayResult();
        return $resultado;
    }
}
