parameters:
#    servicios.example.class: Proces\ServiciosBundle\Example

services:
#    servicios.example:
#        class: %servicios.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
