pasosoferta:
    path:     /
    defaults: { _controller: "OfertaBundle:PasosOferta:index" }

pasosoferta_show:
    path:     /{id}/show/{oferta}
    defaults: { _controller: "OfertaBundle:PasosOferta:show", oferta: null }

pasosoferta_new:
    path:     /new/{oferta}
    defaults: { _controller: "OfertaBundle:PasosOferta:new", oferta: null }

pasosoferta_create:
    path:     /create/{oferta}
    defaults: { _controller: "OfertaBundle:PasosOferta:create", oferta: null }
    requirements: { _method: post }

pasosoferta_edit:
    path:     /{id}/edit/{oferta}
    defaults: { _controller: "OfertaBundle:PasosOferta:edit", oferta: null }

pasosoferta_update:
    path:     /{id}/update/{oferta}
    defaults: { _controller: "OfertaBundle:PasosOferta:update", oferta: null }
    requirements: { _method: post|put }

pasosoferta_delete:
    path:     /{id}/delete/{oferta}
    defaults: { _controller: "OfertaBundle:PasosOferta:delete", oferta: null }
    requirements: { _method: post|delete }
